/* ==========================================================
   Grazie al Cactus · catalogo
   Qui aggiungi, togli o segni come venduti i pezzi.
   I PREZZI SONO SEGNAPOSTO: sostituiscili con quelli reali.
   Se non vuoi mostrare i prezzi, togli la riga "price".
   ========================================================== */

const PRODOTTI = [
  {
    id: "farfalla-oro",
    name: "Farfalla d'oro",
    tag: "Novità",
    price: 26,
    img: "img/farfalla-oro",
    alt: "Latta rosa con una farfalla dorata in rilievo e una sansevieria cilindrica intrecciata",
    desc: "Latta rosa con farfalla dorata in rilievo e bordo oro. Dentro, una sansevieria intrecciata a treccia: elegante e quasi indistruttibile.",
    sold: false,
  },
  {
    id: "blu-porcellana",
    name: "Blu porcellana",
    tag: "Novità",
    price: 24,
    img: "img/blu-porcellana",
    alt: "Latta con découpage floreale blu e bianco stile porcellana, con un'opuntia a due pale",
    desc: "Découpage blu e bianco che ricorda la porcellana antica. Con un'opuntia a due pale, il cactus con le orecchie da coniglio.",
    sold: false,
  },
  {
    id: "oro-grezzo",
    name: "Oro grezzo",
    tag: "Effetto pietra",
    price: 22,
    img: "img/oro-grezzo",
    alt: "Latta con finitura oro e bianco a rilievo effetto roccia, con due cactus colonnari dorati",
    desc: "Latta piccola con rilievi materici bianchi e oro, come una pietra grezza. Due cactus colonnari dalle spine dorate.",
    sold: false,
  },
  {
    id: "brilla-sempre",
    name: "Brilla sempre",
    tag: "Con dedica",
    price: 22,
    img: "img/brilla-sempre",
    alt: "Latta blu con stelle argentate e la scritta Brilla sempre, accanto a una latta dorata con cactus colonnare",
    desc: "Latta blu notte con stelle in rilievo e scritta a mano, con una succulenta a foglia. Il messaggio si può personalizzare.",
    sold: false,
  },
  {
    id: "barattolo-verde",
    name: "Il barattolo verde",
    tag: "Iconico",
    price: 24,
    img: "img/barattolo-verde",
    alt: "Barattolo di vetro dipinto verde metallizzato con il logo Grazie al Cactus e un cactus ramificato",
    desc: "Vetro recuperato, finitura verde metallizzata e il nostro logo. Con euphorbia ramificata. Altezza circa 14 cm.",
    sold: false,
  },
  {
    id: "fiori-vintage",
    name: "Fiori vintage",
    tag: "Formato grande",
    price: 32,
    img: "img/fiori-vintage",
    alt: "Latta grande con découpage di peonie bianche e viola scuro, con opuntia e cactus tondo, coperchio decorato",
    desc: "Peonie bianche e prugna in découpage su latta grande, con il coperchio decorato che fa da sfondo. Opuntia e cactus tondo.",
    sold: false,
  },
  {
    id: "rose-antiche",
    name: "Rose antiche",
    tag: "Romantico",
    price: 30,
    img: "img/rose-antiche",
    alt: "Latta con découpage di rose rosa e coperchio con una rosa, con haworthia e collana di perle",
    desc: "Rose in stile botanico e bordo rosa, coperchio decorato. Dentro, una haworthia e una collana di perle.",
    sold: false,
  },
  {
    id: "strega-tramonto",
    name: "Strega al tramonto",
    tag: "Edizione Halloween",
    price: 20,
    img: "img/strega-tramonto",
    alt: "Barattolo di vetro con découpage di una strega con gatto nero e luna su sfondo arancio, con haworthia e piccole succulente",
    desc: "Barattolo in vetro con strega, gatto nero e luna in un tramonto color ambra. Haworthia zebrata e piccole succulente.",
    sold: false,
  },
  {
    id: "strega-viola",
    name: "Strega viola",
    tag: "Edizione Halloween",
    price: 20,
    img: "img/strega-viola",
    alt: "Barattolo di vetro con découpage di una strega dai capelli rossi e un campanile, bordi viola, con un cactus a dita",
    desc: "Barattolo in vetro con strega dai capelli rossi e campanile, sfumature viola e magenta. Con un cactus a dita.",
    sold: false,
  },
];
